imports = ["./devshell/modules/rust.nix"]

[devshell]
name = "Rust app"

motd = """
{bold}{106}A Rust app{reset}

$(type -p menu &>/dev/null && menu)
"""

packages = [ "fenix.rust-analyzer" ]

[language.rust]
packageSet = "fenix.stable"
tools = [
  "rustc",
  "cargo",
  "clippy",
  "rustfmt",
  "rust-src",
  "rust-std",
]